const myProjects = [
	{
		title: "Citardel",
		desc: "An Online digital library for students to access learning materials.",
		img: "/assets/citardel.png",
		url: "https://citardel.com",
		category: ["website", "Personal"],
		stack: ["laravel", "mysql", "Tailwind CSS", "AWS EC2", "Livewire"],
	},
	{
		title: "Tely App",
		desc: "A mobile app that shows users the telecom network of each of their contacts.",
		img: "/assets/tely.webp",
		url: "https://play.google.com/store/apps/details?id=com.paulchase.connet",
		category: ["app", "Personal"],
		stack: ["React Native", "Tailwind CSS"],
	},
	{
		title: "Marble Game",
		desc: "A mobile game that a user plays offline to guess if a number is odd or even. Inspiration gotten from Squid game",
		img: "/assets/marble.webp",
		url: "https://play.google.com/store/apps/details?id=com.paulstack.Ali",
		category: ["app", "Personal"],
		stack: ["React Native", "Tailwind CSS"],
		code: "https://github.com/PaulChase/marble_game",
	},
	{
		title: "HR56",
		desc: "A fully fledged SaaS product that streamlines the process of hiring, onboarding and managing empoyees of a company or other companies",
		img: "/assets/hr56.png",
		url: "https://hr56.org",
		category: ["website", "Company"],
		stack: ["React Js", "Tailwind CSS", "Laravel", "Inertiajs", "MySQL"],
	},
	{
		title: "Cliento",
		desc: "A full stack application that allows freelancers to manage their projects and clients in a single dashbaord.",
		img: "/assets/cliento.png",
		category: ["website", "Personal"],
		stack: ["Next Js", "Tailwind CSS", "Laravel", "GraphQL", "MySQL"],
		code: "https://github.com/PaulChase/graphQL-project-mgmt-app",
	},
	{
		title: "NerdStack",
		desc: "A twitter clone for developers and tech geeks with authentication and hierachy structure of the tweets in the database",
		img: "/assets/nerdstack.png",
		category: ["website", "Personal"],
		stack: ["React Js", "Tailwind CSS", "Laravel", "MySQL", "REST API"],
		code: "https://github.com/PaulChase/twitter_clone",
	},
	{
		title: "Spend Buddy",
		desc: "A mobile app that allows users to record and track their expenses to as to cultivate a saving culture.",
		img: "/assets/expense.webp",
		url: "https://play.google.com/store/apps/details?id=com.paulstack.spendbuddy",
		category: ["app", "Personal"],
		stack: ["React Native", "Tailwind CSS"],
		code: "https://github.com/PaulChase/expense-app",
	},
	{
		title: "SearchMedia FM App",
		desc: "A mobile app that I built for our school radio station to allow users to listen to the radio station and also read news articles.",
		img: "/assets/search.png",
		url: "https://play.google.com/store/apps/details?id=com.searchmedia.app",
		category: ["app", "Company"],
		stack: ["React Native", "Tailwind CSS"],
	},
	{
		title: "56bridge",
		desc: "Collaborated with another developer to build this application that allows companies to easily conduct online interviews with candidates.",
		img: "/assets/56Bridge.png",
		category: ["website", "Company"],
		stack: ["Laravel Blade", "Livewire", "Tailwind CSS", "Laravel", "MySQL"],
		url: "https://56bridge.com/",
	},
	{
		title: "Percampus",
		desc: "A online marketplace for students to buy and sell their used books and other items.",
		img: "/assets/percampus.jpeg",
		category: ["website", "Personal"],
		stack: ["Laravel Blade", "Livewire", "Tailwind CSS", "Laravel", "MySQL"],
		code: "https://github.com/PaulChase/percampus",
	},
	{
		title: "Zakyus (the taskscollector)",
		desc: "A web application that allows users to create and manage their tasks on their various projects.",
		img: "/assets/zakyus.png",
		category: ["website", "Personal"],
		stack: ["React Js", "Tailwind CSS", "Laravel", "MySQL", "REST API"],
		code: "https://github.com/PaulChase/zakyus",
	},
	{
		title: "Git Folio",
		desc: "A web application that allows users to generate beautiful portfolio websites from their github profiles.",
		img: "/assets/git-folio.png",
		category: ["website", "Personal"],
		stack: ["React Js", "Tailwind CSS", "Github API", "GraphQL"],
		code: "https://github.com/PaulChase/git-fine",
		url: "https://git-folio.netlify.app",
	},
	{
		title: "Stats Hub",
		desc: "A Frontend application that allows users to visualize Nigerian education data from excel sheets in beautiful charts.",
		img: "/assets/stats.png",
		category: ["website", "Personal"],
		stack: ["Next Js", "Tailwind CSS", "NBS", "Google App script"],
		code: "https://github.com/PaulChase/Nigerian-Statistics-charts",
		url: "https://stats-hub.netlify.app/",
	},
	{
		title: "Spotmate",
		desc: "Joined other developers to build this social network for gym and fitness enthusiasts to connect and share their fitness journey.",
		img: "/assets/spotmate.png",
		category: ["website", "Company"],
		stack: ["Next Js", "Tailwind CSS", "Laravel", "REST API", "MySQL"],
		url: "https://spotmatefrontend.vercel.app/",
	},
];
